# Generated by Django 5.2.6 on 2025-09-22 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='تعداد درخواستی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=10, verbose_name='وضعیت درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='drugs.drug', verbose_name='داروی مورد درخواست')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست دهنده')),
            ],
            options={
                'verbose_name': 'درخواست تبادل',
                'verbose_name_plural': 'درخواست\u200cهای تبادل',
                'ordering': ['-created_at'],
            },
        ),
    ]
