# Generated by Django 5.2.6 on 2025-09-22 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=255, verbose_name='نام ژنریک')),
                ('brand_name', models.CharField(max_length=255, verbose_name='نام تجاری')),
                ('dose', models.CharField(max_length=100, verbose_name='دوز')),
                ('form', models.CharField(help_text='مثال: قرص، کپسول، شربت', max_length=100, verbose_name='شکل دارویی')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='شرکت سازنده')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ (تومان)')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد موجودی')),
                ('batch_number', models.CharField(max_length=100, verbose_name='شماره بچ (Batch Number)')),
                ('storage_conditions', models.TextField(blank=True, null=True, verbose_name='شرایط نگهداری')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('reserved', 'رزرو شده'), ('exchanged', 'تبادل شده')], default='available', max_length=10, verbose_name='وضعیت')),
                ('drug_type', models.CharField(choices=[('surplus', 'مازاد'), ('near_expiry', 'نزدیک به انقضا')], default='surplus', max_length=20, verbose_name='نوع دارو')),
                ('tracking_id', models.CharField(blank=True, editable=False, max_length=5, unique=True, verbose_name='شناسه پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to=settings.AUTH_USER_MODEL, verbose_name='مرکز ثبت کننده')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
                'ordering': ['-created_at'],
            },
        ),
    ]
