# Generated by Django 5.2.6 on 2025-09-22 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='نام تجاری')),
                ('generic_name', models.CharField(max_length=255, verbose_name='نام ژنریک')),
                ('dose', models.CharField(max_length=100, verbose_name='دوز')),
                ('form', models.CharField(max_length=100, verbose_name='شکل دارویی')),
                ('quantity_needed', models.PositiveIntegerField(verbose_name='تعداد مورد نیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/در جریان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست دهنده')),
            ],
        ),
    ]
